FROM alpine:latest

USER root:root

RUN apk update
RUN apk upgrade
RUN apk add nginx
RUN apk add openssl
RUN apk add supervisor
RUN apk add bash

RUN mkdir -p /etc/nginx/ssl
RUN mkdir -p /run/nginx
RUN mkdir /utils
RUN mkdir /www

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
	-subj "/C=BE/ST=Brussels/L=Brussels/O=19/CN=gpladet" \
    -keyout /etc/ssl/private/nginx.key -out /etc/ssl/certs/nginx.crt

RUN chown -R root:root /var/lib/nginx
RUN chown -R root:root /www

COPY ./nginx.conf /etc/nginx
COPY ./launch.sh /utils
COPY ./supervisord.conf /etc/supervisord.conf
COPY ./index.html /www

EXPOSE 80 443

ENTRYPOINT ["bash", "/utils/launch.sh"]
