FROM alpine:latest

USER root:root

RUN apk update
RUN apk upgrade
RUN apk add nginx
RUN apk add supervisor
RUN apk add bash
RUN apk add php7 php7-fpm php7-iconv php7-json php7-mbstring php7-mysqli php7-phar php7-session
RUN apk add openrc wget unzip
RUN apk add mariadb mariadb-client

RUN mkdir -p /run/nginx
RUN mkdir /www

RUN wget https://files.phpmyadmin.net/phpMyAdmin/4.9.7/phpMyAdmin-4.9.7-all-languages.zip
RUN unzip phpMyAdmin-4.9.7-all-languages.zip
RUN rm phpMyAdmin-4.9.7-all-languages.zip
RUN mv phpMyAdmin-4.9.7-all-languages phpmyadmin

RUN chown -R root:root /var/lib/nginx
RUN chown -R root:root /www

RUN mv phpmyadmin /www

COPY ./nginx.conf /etc/nginx
COPY ./supervisord.conf /etc/supervisord.conf
COPY ./config.inc.php /www/phpmyadmin/config.inc.php

EXPOSE 5000

CMD ["/usr/bin/supervisord", "-c", "etc/supervisord.conf"]
