FROM alpine:latest

USER root:root

RUN apk update
RUN apk upgrade
RUN apk add nginx
RUN apk add bash openrc
RUN apk add php7 php7-fpm php7-mcrypt php7-opcache php7-soap php7-openssl php7-gmp
RUN apk add php7-pdo_odbc php7-json php7-dom php7-pdo php7-zip php7-mysqli php7-session 
RUN apk add php7-sqlite3 php7-apcu php7-zlib php7-pdo_pgsql php7-bcmath php7-gd php7-odbc 
RUN apk add php7-pdo_mysql php7-pdo_sqlite php7-gettext php7-xmlreader php7-xmlrpc php7-bz2 
RUN apk add php7-iconv php7-mbstring php7-pdo_dblib php7-curl php7-ctype
RUN apk add openrc wget unzip

RUN mkdir -p /run/nginx
RUN mkdir /www
RUN mkdir /utils

RUN wget https://files.phpmyadmin.net/phpMyAdmin/4.9.7/phpMyAdmin-4.9.7-all-languages.zip
RUN unzip phpMyAdmin-4.9.7-all-languages.zip
RUN rm phpMyAdmin-4.9.7-all-languages.zip
RUN mv phpMyAdmin-4.9.7-all-languages phpmyadmin

RUN chown -R root:root /var/lib/nginx
RUN chown -R root:root /www

RUN mv phpmyadmin /www

COPY ./nginx.conf /etc/nginx
COPY ./config.inc.php /www/phpmyadmin/config.inc.php
COPY ./launch.sh /utils
COPY ./probe.sh /utils

EXPOSE 5000

ENTRYPOINT ["bash", "/utils/launch.sh"]
