apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - image: phpmyadmin
          imagePullPolicy: Never
          name: phpmyadmin
          ports:
            - containerPort: 5000
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - /utils/probe.sh
            initialDelaySeconds: 5
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: phpmyadmin
