FROM alpine:latest

USER root:root

RUN apk update
RUN apk upgrade
RUN apk add nginx
RUN apk add unzip
RUN apk add bash wget
RUN apk add php7 php7-fpm php7-mcrypt php7-opcache php7-soap php7-openssl php7-gmp
RUN apk add php7-pdo_odbc php7-json php7-dom php7-pdo php7-zip php7-mysqli php7-session 
RUN apk add php7-sqlite3 php7-apcu php7-zlib php7-pdo_pgsql php7-bcmath php7-gd php7-odbc 
RUN apk add php7-pdo_mysql php7-pdo_sqlite php7-gettext php7-xmlreader php7-xmlrpc php7-bz2 
RUN apk add php7-iconv php7-mbstring php7-pdo_dblib php7-curl php7-ctype

RUN mkdir -p /run/nginx
RUN mkdir /www
RUN mkdir /utils

RUN chown -R root:root /var/lib/nginx
RUN chown -R root:root /www

RUN wget https://wordpress.org/latest.zip
RUN unzip latest.zip 
RUN mv wordpress /www
RUN rm latest.zip 

COPY ./nginx.conf /etc/nginx
COPY ./wp-config.php /www/wordpress/wp-config.php
COPY ./launch.sh /utils
COPY ./probe.sh /utils

EXPOSE 5050

ENTRYPOINT ["bash", "/utils/launch.sh"]
