apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          imagePullPolicy: Never
          name: wordpress
          ports:
            - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - port: 5050
      protocol: TCP
      targetPort: 5050
  selector:
    app: wordpress
