FROM alpine:latest

RUN apk update
RUN apk upgrade
RUN apk add telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/testing/
RUN apk add bash

COPY ./telegraf.conf /etc/telegraf/telegraf.conf

CMD ["telegraf"]
